target-version = "py314"
line-length = 120
preview = true
fix = true

[lint]
select = ["ALL"]

ignore = [
    "COM812", # Recommended ignore from ruff-format
    "CPY001", # No copyright added yet
    "D203",   # One blank line before class (Google prefers no extra line)
    "D213",   # Multi-line docstring summary on first line
    "E501",   # Line length handled by formatter guidance
    "EM101", # Allow exception messages to be defined in the exception
    "FIX002", # Allow ToDo comments
    "G004", # Allow f-strings in logs
    "TRY003", # Allow to define exception messages outside of the class
    "TRY301", # Allow to raise Exceptions within try blocks
]

pydocstyle.convention = "google"

[lint.per-file-ignores]
"setup.py" = ["PLC0415", "S404", "S603"]
"components/**.py" = [
    "TC002", # kubeflow pipelines dsl needs to be imported without type checking to work correctly
]
"tests/**.py" = [
    "PLR2004", # allow magic number comparisons
    "S101", # allow asserts
    ]

[format]
preview = true
