apiVersion: v1
kind: Pod
metadata:
  name: too-large-pod
  namespace: kubeflow-by-doing
spec:
  restartPolicy: Never
  containers:
    - name: too-large
      image: python:3.12-slim
      command: ["python", "-c", "print('hello')"]
      resources:
        requests:
          cpu: "32"
          memory: "256Gi"
        limits:
          cpu: "32"
          memory: "256Gi"
