apiVersion: v1
kind: Secret
metadata:
  name: artifact-store-credentials
  namespace: kubeflow-by-doing
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin123
  AWS_DEFAULT_REGION: us-east-1
  MLFLOW_S3_ENDPOINT_URL: http://minio.minio.svc.cluster.local:9000
  KBD_S3_ENDPOINT_URL: http://minio.minio.svc.cluster.local:9000
  KBD_ARTIFACT_BUCKET: kubeflow-by-doing
